# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Curious concepts
description: >- # this means to ignore newlines until "baseurl:"
  A technical blog about spring-boot, Kubernetes, Istio and the best software development practises.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.malathi.dev" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

env: production

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-sitemap
  - jekyll-remote-theme
  - jemoji
  - jekyll-include-cache

# Pagination settings
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

minimal_mistakes_skin: neon
repository: "malathit/malathit.github.io"

words_per_minute: 160
comments:
  provider: disqus
  disqus:
    shortname: malathit-github-io

analytics:
  provider: google-gtag
  google:
    tracking_id: G-XF1C6FKK1T

author:
  name     : "Malathi Thangarajan"
  avatar   : "https://s.gravatar.com/avatar/3706ad62b82b6482f64ab6139b0ab6d6?s=80"
  bio      : "I am interested in learning new technologies and writing scalable code."
  location : "Munich, Germany"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/malathit"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/malathit"

include:
  - _pages

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      show_date: true
      sitemap: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: false
      toc: false
      toc_sticky: true
      classes: wide
      header:
        overlay_color: "#282936"
  # categories
  - scope:
      path: categories
    values:
      sitemap: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

after_footer_scripts:
  - /assets/js/vanilla-back-to-top.min.js
  - /assets/js/back-to-top.js
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

breadcrumbs: true

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/